services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: martinanajdovska/unsent-message-project-backend:latest
    restart: always
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
    depends_on:
      - db

  frontend:
    container_name: 'frontend'
    image: martinanajdovska/unsent-message-project-frontend:latest
    restart: always
    ports:
      - '5173:80'
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge