services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    #    kubernetes
    image: martinanajdovska/unsent-message-project-backend:latest
    #    docker
    #    build:
    #      context: ./backend
    #      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
    depends_on:
      - db

  frontend:
    #kubernetes
    image: martinanajdovska/unsent-message-project-frontend:latest

    #docker
    #    build:
    #      context: ./frontend
    #      dockerfile: Dockerfile
    restart: always
    ports:
      - '5173:80'

    #docker
#    volumes:
#      - ./frontend:/usr/share/nginx/html


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge