apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: msg-namespace
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: martinanajdovska/unsent-message-project-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/messages_db
            - name: FRONTEND_URL
              value: "http://localhost"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: postgres-configmap
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: name
                  name: postgres-configmap
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: postgres-secrets
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-secrets
